source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

inhibit_all_warnings!

workspace 'API-SampleApp.xcworkspace'

target 'API-SampleApp' do
    project 'API-SampleApp'
	use_frameworks!
end