source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

inhibit_all_warnings!

workspace 'Prototype.xcworkspace'

target 'Prototype' do
    project 'Prototype'
	use_frameworks!
	pod 'AFNetworking', '~> 3.0'
end